### ISSUE TITLE
Add mounted point to returned information

### ISSUE THREAD

**Issue by pihomeserver** [resin-io/drivelist#11]
Hello,

Can you please add the mounted point ( or drive letter based on OS type (/, /home, C:, etc.)) in returned information ?

Thanks

**Comment by jviotti** [comment]
This is something I've been looking forward to implement for some time. I have a branch with OS X support working. Other OSes coming soon.

**Comment by jviotti** [comment]
@Page- @mkorakakis Any ideas on how to associate a physical drive with a drive letter on Windows?

**Comment by jviotti** [comment]
After some investigation regarding how to associate Windows physical drives with drive letters, we're going to reuse/refactor the following vbscript to perform the work: http://blogs.technet.com/b/heyscriptingguy/archive/2005/05/23/how-can-i-correlate-logical-drives-and-physical-disks.aspx.

**Comment by jviotti** [comment]
Hi @pihomeserver, we implemented mount point support for all supported OSes in https://github.com/resin-io/drivelist/pull/12. Would you mind testing that branch to see if it works for you?

**Comment by pihomeserver** [comment]
Thx. I will test and come back if i got an issue

**Comment by jviotti** [comment]
@pihomeserver Sounds good! `mount point` support landed in v1.3.0.
