### ISSUE TITLE
Disks not found - older diskutil format

### ISSUE THREAD

**Issue by boban-stjepanovic-mmc** [resin-io/drivelist#35]
In some versions of diskutil there is no paren in disk name line.
`/dev/disk0` instead of `/dev/disk0 (internal, physical):`
Could this be fixed by changing darwin.sh get_until_paren pattern to match paren or end of line?
I tried with `\\(|$` and it found both cases.

**Comment by jviotti** [comment]
@boban-stjepanovic-mmc Thanks for the issue. Does `drivelist` fails if the disk name line doesn't have a paren currently?

**Comment by jviotti** [comment]
Hm, just test it out and it doesn't get the drive at all if no paren.

Does it include the trailing colon when the drive doesn't have parens? E.g: `/dev/disk0:` or just `/dev/disk0`?

**Comment by boban-stjepanovic-mmc** [comment]
There is no trailing colon, just `/dev/disk0`

**Comment by jviotti** [comment]
@boban-stjepanovic-mmc Your solution looks good. Would like to send a pull request?

**Comment by jviotti** [comment]
Thanks for the PR. I'll release a new version today and let you know.

**Comment by boban-stjepanovic-mmc** [comment]
Thanks

**Comment by jviotti** [comment]
@boban-stjepanovic-mmc I've released `v2.0.0` to NPM. 

In case you were using the previous version, there is a single breaking change:

- `drivelist.isSystem()` was removed, and there is a new `system` property in the returned drives.

**Comment by jviotti** [comment]
Closing this issue since the PR was merged.
