### ISSUE TITLE
Script fails to run if path to module contains space

### ISSUE THREAD

**Issue by boban-stjepanovic-mmc** [resin-io/drivelist#39]
`script.run` fails if there is space in path to module directory.
`/projects/drivelist test/node_modules/drivelist/scripts/darwin.sh` will try to execute until to space
`[Error: Command failed: /bin/sh: /projects/drivelist: No such file or directory]`

Possible solution is to escape spaces in script paths scripts.coffee:10
`darwin: path.join(scriptsPath, 'darwin.sh').replace /[ ]/g, '\\ '`

**Comment by jviotti** [comment]
@boban-stjepanovic-mmc Thanks for the issue. I'll fix this tomorrow and let you know!

**Comment by jviotti** [comment]
@boban-stjepanovic-mmc Fixed and published `v2.0.2` to npm!
