### ISSUE TITLE
error reading SD card on rpi2

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/drivelist#45]
01.12.15 19:13:04 [+0000] Unhandled rejection Error: lsblk: /dev/sda: not a block device
01.12.15 19:13:04 [+0000] lsblk: /dev/sda: not a block device
01.12.15 19:13:04 [+0000] lsblk: /dev/sda: not a block device
01.12.15 19:13:04 [+0000]
01.12.15 19:13:04 [+0000] at /usr/src/app/node_modules/drivelist-scanner/node_modules/drivelist/build/scripts.js:27:23
01.12.15 19:13:04 [+0000] at ChildProcess.exithandler (child_process.js:194:7)
01.12.15 19:13:04 [+0000] at emitTwo (events.js:87:13)
01.12.15 19:13:04 [+0000] at ChildProcess.emit (events.js:172:7)
01.12.15 19:13:04 [+0000] at maybeClose (internal/child_process.js:817:16)
01.12.15 19:13:04 [+0000] at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by jviotti** [comment]
Closing as reported to be sporadic. We'll re-open if it happens again.
