### ISSUE TITLE
mountpoint has a dangling comma

### ISSUE THREAD

**Issue by tborychowski** [resin-io/drivelist#46]
this code `| tr '\n' ','` in [this line](https://github.com/resin-io/drivelist/blob/master/scripts/linux.sh#L17) seems to be adding a comma at the end of the mountpoint name in linux.
So instead of `/` I get `/,`
Is that intentional?

**Comment by jviotti** [comment]
@tborychowski Thanks for reaching out.

A trailing comma after the mount point is not expected. I'm unable to reproduce under an Ubuntu 14.02 box.

Do you get the trailing comma when running the `linux.sh` script directly, or by running the `example.js` file in the top level directory?

Can you post the output of `grep "^$device" /proc/mounts | cut -d ' ' -f 2`, replacing `$device` with the corresponding device?

The `\n` to `,` replacement with `tr` is meant to handle cases where a drive has many mount points.

**Comment by tborychowski** [comment]
Hi @jviotti,
Actually I was using the node module in my project, but it seems that the script itself is throwing the comma.
Here's my output from running the script:

```sh
/node_modules/drivelist/scripts> ./linux.sh 
device: /dev/sda
description: KINGSTON SV300S3
size: 111.8G
mountpoint: /,
system: True

device: /dev/sdc
description: TOSHIBA DT01ACA2
size: 1.8T
mountpoint: /mnt/Magazyn,
system: True
```

And here's the output from the command:
```sh
> grep /dev/sda /proc/mounts | cut -d ' ' -f 2
/
> grep /dev/sdc /proc/mounts | cut -d ' ' -f 2
/mnt/Magazyn
```
Maybe the parser could trim the trailing commas?

**Comment by jviotti** [comment]
Yeah, I'll make the parser catch this edge case and submit a PR very soon. I'll let you know so you can test from your side to confirm!

**Comment by jviotti** [comment]
@tborychowski I've just sent a PR. Can you confirm it fixes the issue for you?

**Comment by tborychowski** [comment]
@jviotti, yes, that fixed my issue, thanks!

**Comment by jviotti** [comment]
@tborychowski Wonderful, I'll publish a new version in NPM for you.

**Comment by tborychowski** [comment]
thanks! :-)

**Comment by jviotti** [comment]
@tborychowski v2.0.5 is live with your fix! Thanks a lot for the bug report!
