### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by pihomeserver** [resin-io/drivelist#5]
Hello,

Is there a way to get more information on disks like :
- Free space
- Filesystem type (vfat, ext4, hfs, etc.)
- Mounted point or drive letter based on OS type (/, /home, C:, etc.)

**Comment by Eusebius1920** [comment]
+1

**Comment by jviotti** [comment]
@pihomeserver Thanks for reaching out!

The mounted point would be something I'd be interested in seeing in `drivelist`. Do you mind creating a new issue for that feature?

About filesystem type, a drive can have multiple partitions, and each of them can have a different type, therefore the result would be either inaccurate or missing in some cases.

Regarding the free space, it's similar to the above one. We can only consider free space in terms of a single partition, but a drive can have multiple of them, each with different free space information.

For the two cases mentioned above, I recommend taking a look at https://github.com/jhermsmeier/node-mbr.

**Comment by pihomeserver** [comment]
Ok that's a point of view. I thought more about a disk is splitted in partitions, each partition has a type and free space. The mount point (or letter drive for windows systems) could be one information except if the partition is not mounted/available.

You want a dedicated issue for mounted point only ? (to not make a mistake ;-))

**Comment by jviotti** [comment]
> Ok that's a point of view. I thought more about a disk is splitted in partitions, each partition has a type and free space. The mount point (or letter drive for windows systems) could be one information except if the partition is not mounted/available.

Yeah, but I think that deviates a bit from the purpose of `drivelist`, which is finding the disks, but not worrying about its contents. I suggest that you create a new module that given a `drivelist` drive object, it returns a new object with expanded information. You can then map the output of `drivelist` to get the result you want.

> You want a dedicated issue for mounted point only ? (to not make a mistake ;-))

That's right :)

**Comment by pihomeserver** [comment]
Done
